"""Explainable decision engine domain."""

from hephaestus.decision.analysis import (
    CountMetric,
    DecisionStats,
    DecisionSummary,
    aggregate_decision_stats,
    most_common_rationale,
    most_common_rejection_reason,
    summarize_decisions,
)
from hephaestus.decision.builder import (
    DecisionTraceBuilder,
    build_budget_decision,
    build_context_selection_decision,
    build_model_routing_decision,
    build_model_routing_error_decision,
    build_optimization_decision,
    build_safety_approval_decision,
    build_safety_policy_decision,
    build_task_selection_decision,
)
from hephaestus.decision.renderer import (
    build_decision_stats_renderable,
    build_decision_summary_renderable,
    build_run_explanation_renderable,
    render_decision_stats,
    render_decision_summary,
    render_run_explanation,
)
from hephaestus.decision.repository import DecisionTraceRepository
from hephaestus.decision.schemas import (
    BudgetDecision,
    ContextSelectionDecision,
    DecisionAlternative,
    DecisionMetric,
    DecisionTrace,
    DecisionTraceNode,
    DecisionTraceVariant,
    DecisionType,
    MetricValue,
    ModelRoutingDecision,
    OptimizationDecision,
    SafetyDecision,
    TaskSelectionDecision,
    metric,
)

__all__ = [
    "BudgetDecision",
    "ContextSelectionDecision",
    "CountMetric",
    "DecisionStats",
    "DecisionSummary",
    "DecisionAlternative",
    "DecisionMetric",
    "DecisionTrace",
    "DecisionTraceBuilder",
    "DecisionTraceNode",
    "DecisionTraceRepository",
    "DecisionTraceVariant",
    "DecisionType",
    "MetricValue",
    "ModelRoutingDecision",
    "OptimizationDecision",
    "SafetyDecision",
    "TaskSelectionDecision",
    "aggregate_decision_stats",
    "build_decision_stats_renderable",
    "build_decision_summary_renderable",
    "build_budget_decision",
    "build_context_selection_decision",
    "build_model_routing_decision",
    "build_model_routing_error_decision",
    "build_optimization_decision",
    "build_safety_approval_decision",
    "build_safety_policy_decision",
    "build_task_selection_decision",
    "build_run_explanation_renderable",
    "metric",
    "most_common_rationale",
    "most_common_rejection_reason",
    "render_decision_stats",
    "render_decision_summary",
    "render_run_explanation",
    "summarize_decisions",
]
